version: '3.3'

services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      TZ: Asia/Jakarta


  mswkm:
    image: rahmatafriayadi/mswkm:1.0.2
    container_name: mswkm
    ports:
      - 3003:3003
    env_file:
      - .env
    environment:
      - PORT=3003
      - DB_USER=root
      - DB_PASS=Mgreen03663!
      - DB_HOST=103.163.139.156
      - DB_PORT=3306
      - DB_NAME=ms_wkm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    